language: php

php:
  - 5.6
  - 7.0
  - 7.1

sudo: false

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

before_script:
  - travis_retry composer self-update
  - travis_wait composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - phpunit --covergae-text --coverage-clover=coverage.clover

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
